### ISSUE TITLE
Assalomu alekum, logoni oldidagi rasm sal pastga tushib ketibdi o'shani to'g'irlab qo'ysak yaxshi bo'lardi

### ISSUE THREAD

**Issue by abdulvakhid** [BORETS2002/bookmark#1]
![image](https://user-images.githubusercontent.com/93217687/176834245-5047ec6f-9e58-41ad-ab78-371b67e7c38e.png)

**Comment by BORETS2002** [comment]
tuzatildi raxmat aytganiz uchun
